version: '3'

services:
  mercadolibre-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: mercadolibre-test
    container_name: mercadolibre-test
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
    command: sh -c "npm run build && npm run start"